packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.10.4
  "@trpc/server": ^11.7.1
  better-auth: ^1.3.34
  dotenv: ^17.2.3
  zod: ^4.1.12
  typescript: ^5.9.3
  tsdown: ^0.15.12
  wrangler: ^4.46.0
  "@trpc/client": ^11.7.1
