/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as authenticatedBoardsIndexRouteImport } from './routes/(authenticated)/boards/index'
import { Route as authenticatedLinksIdRouteImport } from './routes/(authenticated)/links/$id'
import { Route as authenticatedBoardsIdRouteImport } from './routes/(authenticated)/boards/$id'
import { Route as publicauthSignInIndexRouteImport } from './routes/(public)/(auth)/sign-in/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBoardsIndexRoute =
  authenticatedBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedLinksIdRoute = authenticatedLinksIdRouteImport.update({
  id: '/links/$id',
  path: '/links/$id',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBoardsIdRoute = authenticatedBoardsIdRouteImport.update({
  id: '/boards/$id',
  path: '/boards/$id',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicauthSignInIndexRoute = publicauthSignInIndexRouteImport.update({
  id: '/(public)/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/': typeof publicIndexRoute
  '/boards/$id': typeof authenticatedBoardsIdRoute
  '/links/$id': typeof authenticatedLinksIdRoute
  '/boards': typeof authenticatedBoardsIndexRoute
  '/sign-in': typeof publicauthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/': typeof publicIndexRoute
  '/boards/$id': typeof authenticatedBoardsIdRoute
  '/links/$id': typeof authenticatedLinksIdRoute
  '/boards': typeof authenticatedBoardsIndexRoute
  '/sign-in': typeof publicauthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/boards/$id': typeof authenticatedBoardsIdRoute
  '/(authenticated)/links/$id': typeof authenticatedLinksIdRoute
  '/(authenticated)/boards/': typeof authenticatedBoardsIndexRoute
  '/(public)/(auth)/sign-in/': typeof publicauthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/dashboard'
    | '/'
    | '/boards/$id'
    | '/links/$id'
    | '/boards'
    | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/boards/$id'
    | '/links/$id'
    | '/boards'
    | '/sign-in'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/login'
    | '/(authenticated)/dashboard'
    | '/(public)/'
    | '/(authenticated)/boards/$id'
    | '/(authenticated)/links/$id'
    | '/(authenticated)/boards/'
    | '/(public)/(auth)/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  publicIndexRoute: typeof publicIndexRoute
  publicauthSignInIndexRoute: typeof publicauthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/boards/': {
      id: '/(authenticated)/boards/'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof authenticatedBoardsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/links/$id': {
      id: '/(authenticated)/links/$id'
      path: '/links/$id'
      fullPath: '/links/$id'
      preLoaderRoute: typeof authenticatedLinksIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/boards/$id': {
      id: '/(authenticated)/boards/$id'
      path: '/boards/$id'
      fullPath: '/boards/$id'
      preLoaderRoute: typeof authenticatedBoardsIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(auth)/sign-in/': {
      id: '/(public)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicauthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedBoardsIdRoute: typeof authenticatedBoardsIdRoute
  authenticatedLinksIdRoute: typeof authenticatedLinksIdRoute
  authenticatedBoardsIndexRoute: typeof authenticatedBoardsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedBoardsIdRoute: authenticatedBoardsIdRoute,
  authenticatedLinksIdRoute: authenticatedLinksIdRoute,
  authenticatedBoardsIndexRoute: authenticatedBoardsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  publicIndexRoute: publicIndexRoute,
  publicauthSignInIndexRoute: publicauthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
